import React from 'react';
import { ScrollPanel } from 'primereact/scrollpanel';
import { Image } from 'primereact/image';

interface HDRProps {}
interface HDRState {}

export class HDR extends React.Component<HDRProps, HDRState> {
  render() {
    return (
      <div className="grid grid-nogutter surface-section text-800">
        <div className="col-12 md:col-6 p-6 text-center md:text-left flex align-items-center ">
          <section>
            <span className="block text-6xl font-bold mb-1">HewDraw Remix</span>
            <div className="text-6l text-primary font-bold mb-3">
              Open-Source Development
            </div>
            <ScrollPanel
              style={{
                height: '320px',
                maxWidth: '100%',
                wordBreak: 'break-word',
              }}
            >
              <p>
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
                HDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDRHDR
              </p>
            </ScrollPanel>
          </section>
        </div>
        <div className="col-12 md:col-6 overflow-hidden">
          <img
            src="https://cdn.discordapp.com/attachments/1034999594012127342/1113604190946742293/Kaylaspook-020.jpg"
            alt="hero-1"
            className="md:ml-auto block md:h-full"
            style={{
              clipPath: 'polygon(8% 0, 100% 0%, 100% 100%, 0 100%)',
              maxWidth: '100%',
            }}
          />
        </div>
      </div>
    );
  }
}
